development:
development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  development:
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: coinapp_production
